import { RegisterRoutes } from './routes'; 
const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');



const app = express();
app.use(cors());
console.log('Server Script Started')

// connect to mongoDB
mongoose.connect('mongodb://localhost:27017/Item', { useNewUrlParser: true, useUnifiedTopology: true })
  .then(() => console.log('Database connected!'))
  .catch((err: any) => console.log(err));

  mongoose.connection.on('connected', () => {
    console.log('Mongoose connected');
  });
  
  mongoose.connection.on('error', (err: any) => {
    console.log('Mongoose connection error: ' + err);
  });
  
  mongoose.connection.on('disconnected', () => {
    console.log('Mongoose disconnected');
  });

// Use express.json() middleware to parse JSON request bodies
app.use(express.json());

// Register the routes generated by TSOA
RegisterRoutes(app);

app.listen(7071, () => { 
  console.log('Server is listening on port 7071');
});