"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var routes_1 = require("./routes");
var express = require('express');
var mongoose = require('mongoose');
var cors = require('cors');
var app = express();
app.use(cors());
console.log('Server Script Started');
// connect to mongoDB
mongoose.connect('mongodb://localhost:27017/Item', { useNewUrlParser: true, useUnifiedTopology: true })
    .then(function () { return console.log('Database connected!'); })
    .catch(function (err) { return console.log(err); });
mongoose.connection.on('connected', function () {
    console.log('Mongoose connected');
});
mongoose.connection.on('error', function (err) {
    console.log('Mongoose connection error: ' + err);
});
mongoose.connection.on('disconnected', function () {
    console.log('Mongoose disconnected');
});
// Use express.json() middleware to parse JSON request bodies
app.use(express.json());
// Register the routes generated by TSOA
(0, routes_1.RegisterRoutes)(app);
app.listen(7071, function () {
    console.log('Server is listening on port 7071');
});
